apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypersonalwebsite
  labels:
    app: mypersonalwebsite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypersonalwebsite
  template:
    metadata:
      name: mypersonalwebsite
      labels:
        app: mypersonalwebsite
    spec:
      containers:
      - name: mypersonalwebsite
        image: ahmedsayedtalib/mypersonalwebsite:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mypersonalwebsite-service
  labels:
    app: mypersonalwebsite
spec:
  selector:
    app: mypersonalwebsite
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
